server:
    port: 3031
spring:
    main:
        allow-bean-definition-overriding: true
    application:
        name: approval-poc
# temporal specific configs
    temporal:
        namespace: default
        connection:
            target: 127.0.0.1:7233
        workersAutoDiscovery:
            packages: com.malchun.approval.poc.process
logging.level.com.malchun.approval.poc: DEBUG